version: "3"
services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

#  app:
#    build: .
#    links:
#      - redis
#    depends_on:
#      - redis
#    ports:
#      - "5000:5000"